/* ============================================================
   ヒビノネ写真館 サイト設定ファイル
   ------------------------------------------------------------
   写真・文言・料金・FAQ・Instagram など、あとから変わる情報は
   すべてこのファイルにまとめています。
   ここを書き換えて保存するだけでサイトに反映されます。
   ============================================================ */

const SITE_CONFIG = {

  /* ----------------------------------------------------------
     基本情報
  ---------------------------------------------------------- */
  studioName: "ヒビノネ写真館",
  studioNameEn: "HIBINONE PHOTO STUDIO",
  photographer: "Keiko",
  area: "Miyazaki / Miyakonojo",

  /* Instagram（URLが決まったら書き換える） */
  instagramUrl: "https://www.instagram.com/hibi_none/?hl=ja",

  /* ----------------------------------------------------------
     お問い合わせフォーム送信設定
     ------------------------------------------------------------
     Web3Forms（https://web3forms.com）で無料のアクセスキーを
     取得し、下の accessKey に貼り付けると、
     tourico4696@gmail.com にメールが届くようになります。
     （キー取得時に受信先メールアドレスを登録するため、
       HTML内にメールアドレスを書く必要がありません）
  ---------------------------------------------------------- */
  form: {
    provider: "web3forms",
    endpoint: "https://api.web3forms.com/submit",
    accessKey: "",            // ← ここにWeb3Formsのアクセスキーを貼る
    subjectPrefix: "【ヒビノネ写真館】"
  },

  /* ----------------------------------------------------------
     ファーストビューのカルーセル写真
     size: "tall"（縦長・大）/ "wide"（横長）/ "small"（小さめ）
  ---------------------------------------------------------- */
  heroPhotos: [
    { src: "images/photos/bridal-top.webp",          size: "wide",  alt: "光の入る室内で見つめ合う新郎新婦" },
    { src: "images/photos/asahi210.webp",            size: "wide",  alt: "桜並木の下でおんぶをして笑い合う家族" },
    { src: "images/photos/tutumi077.webp",           size: "small", alt: "ニット帽をかぶった双子の赤ちゃんのニューボーンフォト" },
    { src: "images/photos/takami_753_073.webp",      size: "tall",  alt: "七五三で水風船を見つめる男の子" },
    { src: "images/photos/morimocha029.webp",        size: "small", alt: "木のテーブルに並んだ出来たてのたこ焼き" },
    { src: "images/photos/hukuoka083.webp",          size: "wide",  alt: "街並みの中を歩くウェディングドレスの新郎新婦" },
    { src: "images/photos/temazushi092.webp",        size: "tall",  alt: "カウンターで寿司を握る職人の手元" },
    { src: "images/photos/sakai114.webp",            size: "small", alt: "母親に抱かれて笑う赤ちゃん" },
    { src: "images/photos/dsc01753.webp",            size: "wide",  alt: "工房で微笑む店主の夫婦" },
    { src: "images/photos/muraoka260403_008.webp",   size: "small", alt: "桜の下でランドセルを背負って笑う兄妹" },
    { src: "images/photos/momochan_seijin002.webp",  size: "wide",  alt: "日本庭園の縁側に座る振袖姿の女性" },
    { src: "images/photos/kaseda038.webp",           size: "small", alt: "古民家の窓辺に並ぶ着物姿の子どもたち" },
    { src: "images/photos/kubota477.webp",           size: "tall",  alt: "緑あふれる会場で寄り添う新郎新婦" },
    { src: "images/photos/koukun260228_061.webp",    size: "wide",  alt: "田んぼのそばでサッカーボールと遊ぶ男の子" },
    { src: "images/photos/uchimura018.webp",         size: "small", alt: "木の窓からそっと外をのぞく子ども" }
  ],

  /* ----------------------------------------------------------
     ファーストビューのランダム候補写真
     ページを開くたびに、この中から36枚をランダム表示します
  ---------------------------------------------------------- */
  heroPool: [
    { src: "images/scenes/bridal/bridal001.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal002.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal003.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal004.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal005.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal006.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal007.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal008.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal009.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal010.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal011.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal012.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal013.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal014.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal015.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal016.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal017.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal018.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal019.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal020.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal021.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal023.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal024.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal025.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal026.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal028.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal029.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal030.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal031.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal032.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal033.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal034.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal035.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal036.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal037.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal038.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal039.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal040.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal041.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal042.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal043.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal044.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal045.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal046.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal047.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal048.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal049.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal050.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal051.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal052.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal053.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal054.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal055.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal056.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal057.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal059.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal060.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal061.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal062.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal063.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal065.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal066.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal067.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal068.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal069.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal070.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal072.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal073.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal074.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal075.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal076.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal077.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal078.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal079.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal080.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal081.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal082.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal083.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal084.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal085.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal086.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal087.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal088.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal090.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal091.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal092.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal093.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal094.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal095.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal096.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal097.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal098.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal099.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal100.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal101.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal102.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal103.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal104.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal105.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal106.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal107.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal108.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal109.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal110.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal111.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal112.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal113.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal114.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal115.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal116.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal117.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal118.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal119.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal120.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal121.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal122.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal123.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal124.webp", size: "tall" },
    { src: "images/scenes/bridal/bridal125.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal126.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal127.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal128.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal129.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal130.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal131.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal132.webp", size: "wide" },
    { src: "images/scenes/bridal/bridal133.webp", size: "wide" },
    { src: "images/scenes/coming/coming001.webp", size: "wide" },
    { src: "images/scenes/coming/coming002.webp", size: "wide" },
    { src: "images/scenes/coming/coming003.webp", size: "wide" },
    { src: "images/scenes/coming/coming004.webp", size: "wide" },
    { src: "images/scenes/coming/coming005.webp", size: "wide" },
    { src: "images/scenes/coming/coming006.webp", size: "wide" },
    { src: "images/scenes/coming/coming007.webp", size: "wide" },
    { src: "images/scenes/coming/coming008.webp", size: "wide" },
    { src: "images/scenes/coming/coming009.webp", size: "wide" },
    { src: "images/scenes/coming/coming010.webp", size: "wide" },
    { src: "images/scenes/coming/coming011.webp", size: "wide" },
    { src: "images/scenes/coming/coming012.webp", size: "wide" },
    { src: "images/scenes/coming/coming013.webp", size: "wide" },
    { src: "images/scenes/coming/coming014.webp", size: "wide" },
    { src: "images/scenes/coming/coming015.webp", size: "wide" },
    { src: "images/scenes/coming/coming016.webp", size: "wide" },
    { src: "images/scenes/coming/coming017.webp", size: "wide" },
    { src: "images/scenes/daily/daily001.webp", size: "tall" },
    { src: "images/scenes/daily/daily002.webp", size: "wide" },
    { src: "images/scenes/daily/daily003.webp", size: "tall" },
    { src: "images/scenes/daily/daily004.webp", size: "wide" },
    { src: "images/scenes/daily/daily005.webp", size: "wide" },
    { src: "images/scenes/daily/daily006.webp", size: "tall" },
    { src: "images/scenes/daily/daily007.webp", size: "tall" },
    { src: "images/scenes/daily/daily008.webp", size: "tall" },
    { src: "images/scenes/daily/daily009.webp", size: "tall" },
    { src: "images/scenes/daily/daily010.webp", size: "tall" },
    { src: "images/scenes/daily/daily011.webp", size: "tall" },
    { src: "images/scenes/daily/daily012.webp", size: "tall" },
    { src: "images/scenes/daily/daily013.webp", size: "tall" },
    { src: "images/scenes/daily/daily014.webp", size: "tall" },
    { src: "images/scenes/daily/daily015.webp", size: "tall" },
    { src: "images/scenes/daily/daily016.webp", size: "tall" },
    { src: "images/scenes/daily/daily017.webp", size: "wide" },
    { src: "images/scenes/daily/daily018.webp", size: "wide" },
    { src: "images/scenes/daily/daily019.webp", size: "wide" },
    { src: "images/scenes/daily/daily020.webp", size: "wide" },
    { src: "images/scenes/daily/daily021.webp", size: "wide" },
    { src: "images/scenes/daily/daily022.webp", size: "wide" },
    { src: "images/scenes/daily/daily023.webp", size: "wide" },
    { src: "images/scenes/daily/daily024.webp", size: "wide" },
    { src: "images/scenes/daily/daily025.webp", size: "wide" },
    { src: "images/scenes/daily/daily026.webp", size: "wide" },
    { src: "images/scenes/daily/daily027.webp", size: "wide" },
    { src: "images/scenes/daily/daily028.webp", size: "wide" },
    { src: "images/scenes/daily/daily029.webp", size: "wide" },
    { src: "images/scenes/daily/daily030.webp", size: "wide" },
    { src: "images/scenes/daily/daily031.webp", size: "wide" },
    { src: "images/scenes/daily/daily032.webp", size: "wide" },
    { src: "images/scenes/daily/daily033.webp", size: "wide" },
    { src: "images/scenes/daily/daily034.webp", size: "wide" },
    { src: "images/scenes/daily/daily035.webp", size: "wide" },
    { src: "images/scenes/daily/daily036.webp", size: "wide" },
    { src: "images/scenes/daily/daily037.webp", size: "wide" },
    { src: "images/scenes/daily/daily038.webp", size: "wide" },
    { src: "images/scenes/daily/daily039.webp", size: "wide" },
    { src: "images/scenes/daily/daily040.webp", size: "wide" },
    { src: "images/scenes/daily/daily041.webp", size: "wide" },
    { src: "images/scenes/memory/memory001.webp", size: "tall" },
    { src: "images/scenes/memory/memory002.webp", size: "tall" },
    { src: "images/scenes/memory/memory003.webp", size: "tall" },
    { src: "images/scenes/memory/memory004.webp", size: "tall" },
    { src: "images/scenes/memory/memory005.webp", size: "tall" },
    { src: "images/scenes/memory/memory006.webp", size: "tall" },
    { src: "images/scenes/memory/memory007.webp", size: "tall" },
    { src: "images/scenes/memory/memory008.webp", size: "tall" },
    { src: "images/scenes/memory/memory009.webp", size: "tall" },
    { src: "images/scenes/memory/memory010.webp", size: "tall" },
    { src: "images/scenes/memory/memory011.webp", size: "tall" },
    { src: "images/scenes/memory/memory012.webp", size: "tall" },
    { src: "images/scenes/memory/memory013.webp", size: "tall" },
    { src: "images/scenes/memory/memory014.webp", size: "tall" },
    { src: "images/scenes/memory/memory015.webp", size: "tall" },
    { src: "images/scenes/memory/memory016.webp", size: "tall" },
    { src: "images/scenes/memory/memory017.webp", size: "tall" },
    { src: "images/scenes/memory/memory018.webp", size: "tall" },
    { src: "images/scenes/memory/memory019.webp", size: "tall" },
    { src: "images/scenes/memory/memory020.webp", size: "tall" },
    { src: "images/scenes/memory/memory021.webp", size: "tall" },
    { src: "images/scenes/memory/memory022.webp", size: "tall" },
    { src: "images/scenes/memory/memory023.webp", size: "tall" },
    { src: "images/scenes/memory/memory024.webp", size: "tall" },
    { src: "images/scenes/memory/memory025.webp", size: "tall" },
    { src: "images/scenes/memory/memory026.webp", size: "tall" },
    { src: "images/scenes/memory/memory027.webp", size: "tall" },
    { src: "images/scenes/memory/memory028.webp", size: "tall" },
    { src: "images/scenes/memory/memory029.webp", size: "tall" },
    { src: "images/scenes/memory/memory030.webp", size: "tall" },
    { src: "images/scenes/memory/memory031.webp", size: "tall" },
    { src: "images/scenes/memory/memory032.webp", size: "tall" },
    { src: "images/scenes/memory/memory033.webp", size: "tall" },
    { src: "images/scenes/memory/memory034.webp", size: "tall" },
    { src: "images/scenes/memory/memory035.webp", size: "wide" },
    { src: "images/scenes/memory/memory036.webp", size: "tall" },
    { src: "images/scenes/memory/memory037.webp", size: "tall" },
    { src: "images/scenes/memory/memory038.webp", size: "tall" },
    { src: "images/scenes/memory/memory039.webp", size: "tall" },
    { src: "images/scenes/memory/memory040.webp", size: "tall" },
    { src: "images/scenes/memory/memory041.webp", size: "tall" },
    { src: "images/scenes/memory/memory042.webp", size: "tall" },
    { src: "images/scenes/memory/memory043.webp", size: "wide" },
    { src: "images/scenes/memory/memory044.webp", size: "tall" },
    { src: "images/scenes/memory/memory045.webp", size: "wide" },
    { src: "images/scenes/memory/memory046.webp", size: "tall" },
    { src: "images/scenes/memory/memory047.webp", size: "tall" },
    { src: "images/scenes/memory/memory048.webp", size: "tall" },
    { src: "images/scenes/memory/memory049.webp", size: "wide" },
    { src: "images/scenes/memory/memory050.webp", size: "wide" },
    { src: "images/scenes/memory/memory051.webp", size: "tall" },
    { src: "images/scenes/memory/memory052.webp", size: "tall" },
    { src: "images/scenes/memory/memory053.webp", size: "tall" },
    { src: "images/scenes/memory/memory054.webp", size: "tall" },
    { src: "images/scenes/memory/memory055.webp", size: "tall" },
    { src: "images/scenes/memory/memory056.webp", size: "tall" },
    { src: "images/scenes/memory/memory057.webp", size: "tall" },
    { src: "images/scenes/memory/memory058.webp", size: "tall" },
    { src: "images/scenes/memory/memory059.webp", size: "tall" },
    { src: "images/scenes/memory/memory060.webp", size: "tall" },
    { src: "images/scenes/memory/memory061.webp", size: "tall" },
    { src: "images/scenes/memory/memory062.webp", size: "tall" },
    { src: "images/scenes/memory/memory063.webp", size: "tall" },
    { src: "images/scenes/memory/memory064.webp", size: "tall" },
    { src: "images/scenes/memory/memory065.webp", size: "tall" },
    { src: "images/scenes/memory/memory066.webp", size: "tall" },
    { src: "images/scenes/memory/memory067.webp", size: "tall" },
    { src: "images/scenes/memory/memory068.webp", size: "tall" },
    { src: "images/scenes/memory/memory069.webp", size: "tall" },
    { src: "images/scenes/memory/memory070.webp", size: "tall" },
    { src: "images/scenes/memory/memory071.webp", size: "tall" },
    { src: "images/scenes/memory/memory072.webp", size: "tall" },
    { src: "images/scenes/memory/memory073.webp", size: "tall" },
    { src: "images/scenes/memory/memory074.webp", size: "tall" },
    { src: "images/scenes/memory/memory075.webp", size: "tall" },
    { src: "images/scenes/memory/memory076.webp", size: "tall" },
    { src: "images/scenes/memory/memory077.webp", size: "tall" },
    { src: "images/scenes/memory/memory078.webp", size: "tall" },
    { src: "images/scenes/memory/memory079.webp", size: "tall" },
    { src: "images/scenes/memory/memory080.webp", size: "tall" },
    { src: "images/scenes/memory/memory081.webp", size: "tall" },
    { src: "images/scenes/memory/memory082.webp", size: "tall" },
    { src: "images/scenes/memory/memory083.webp", size: "tall" },
    { src: "images/scenes/memory/memory084.webp", size: "tall" },
    { src: "images/scenes/memory/memory085.webp", size: "tall" },
    { src: "images/scenes/memory/memory086.webp", size: "tall" },
    { src: "images/scenes/memory/memory087.webp", size: "tall" },
    { src: "images/scenes/memory/memory088.webp", size: "tall" },
    { src: "images/scenes/memory/memory089.webp", size: "tall" },
    { src: "images/scenes/memory/memory090.webp", size: "tall" },
    { src: "images/scenes/memory/memory091.webp", size: "tall" },
    { src: "images/scenes/memory/memory092.webp", size: "tall" },
    { src: "images/scenes/memory/memory093.webp", size: "tall" },
    { src: "images/scenes/memory/memory094.webp", size: "tall" },
    { src: "images/scenes/memory/memory095.webp", size: "tall" },
    { src: "images/scenes/memory/memory096.webp", size: "tall" },
    { src: "images/scenes/memory/memory097.webp", size: "tall" },
    { src: "images/scenes/memory/memory098.webp", size: "tall" },
    { src: "images/scenes/memory/memory099.webp", size: "tall" },
    { src: "images/scenes/memory/memory100.webp", size: "tall" },
    { src: "images/scenes/memory/memory101.webp", size: "tall" },
    { src: "images/scenes/memory/memory102.webp", size: "tall" },
    { src: "images/scenes/memory/memory103.webp", size: "tall" },
    { src: "images/scenes/memory/memory104.webp", size: "tall" },
    { src: "images/scenes/memory/memory105.webp", size: "tall" },
    { src: "images/scenes/memory/memory106.webp", size: "tall" },
    { src: "images/scenes/memory/memory107.webp", size: "tall" },
    { src: "images/scenes/memory/memory108.webp", size: "tall" },
    { src: "images/scenes/memory/memory109.webp", size: "tall" },
    { src: "images/scenes/memory/memory110.webp", size: "tall" },
    { src: "images/scenes/memory/memory111.webp", size: "tall" },
    { src: "images/scenes/memory/memory112.webp", size: "tall" },
    { src: "images/scenes/memory/memory113.webp", size: "tall" },
    { src: "images/scenes/memory/memory114.webp", size: "tall" },
    { src: "images/scenes/memory/memory115.webp", size: "tall" },
    { src: "images/scenes/memory/memory116.webp", size: "tall" },
    { src: "images/scenes/memory/memory117.webp", size: "tall" },
    { src: "images/scenes/memory/memory118.webp", size: "tall" },
    { src: "images/scenes/memory/memory119.webp", size: "tall" },
    { src: "images/scenes/memory/memory120.webp", size: "tall" },
    { src: "images/scenes/memory/memory121.webp", size: "tall" },
    { src: "images/scenes/memory/memory122.webp", size: "tall" },
    { src: "images/scenes/memory/memory123.webp", size: "tall" },
    { src: "images/scenes/memory/memory124.webp", size: "tall" },
    { src: "images/scenes/memory/memory125.webp", size: "tall" },
    { src: "images/scenes/memory/memory126.webp", size: "tall" },
    { src: "images/scenes/pet/pet001.webp", size: "wide" },
    { src: "images/scenes/pet/pet002.webp", size: "wide" },
    { src: "images/scenes/pet/pet003.webp", size: "wide" },
    { src: "images/scenes/pet/pet004.webp", size: "wide" },
    { src: "images/scenes/pet/pet005.webp", size: "wide" },
    { src: "images/scenes/pet/pet006.webp", size: "wide" },
    { src: "images/scenes/pet/pet007.webp", size: "wide" },
    { src: "images/scenes/pet/pet008.webp", size: "wide" },
    { src: "images/scenes/pet/pet009.webp", size: "wide" },
    { src: "images/scenes/pet/pet010.webp", size: "wide" },
    { src: "images/scenes/pet/pet011.webp", size: "wide" },
    { src: "images/scenes/pet/pet012.webp", size: "wide" },
    { src: "images/scenes/pet/pet013.webp", size: "wide" },
    { src: "images/scenes/pet/pet014.webp", size: "wide" },
    { src: "images/scenes/pet/pet015.webp", size: "wide" },
    { src: "images/scenes/pet/pet016.webp", size: "wide" },
    { src: "images/scenes/pet/pet017.webp", size: "wide" },
    { src: "images/scenes/pet/pet018.webp", size: "wide" },
    { src: "images/scenes/pet/pet019.webp", size: "wide" },
    { src: "images/scenes/pet/pet020.webp", size: "wide" },
    { src: "images/scenes/pet/pet021.webp", size: "wide" },
    { src: "images/scenes/pet/pet022.webp", size: "wide" },
    { src: "images/scenes/pet/pet023.webp", size: "wide" },
    { src: "images/scenes/pet/pet024.webp", size: "wide" },
    { src: "images/scenes/pet/pet025.webp", size: "wide" },
    { src: "images/scenes/pet/pet026.webp", size: "wide" },
    { src: "images/scenes/pet/pet027.webp", size: "wide" },
    { src: "images/scenes/pet/pet028.webp", size: "wide" },
    { src: "images/scenes/pet/pet029.webp", size: "wide" },
    { src: "images/scenes/pet/pet030.webp", size: "wide" },
    { src: "images/scenes/pet/pet031.webp", size: "wide" },
    { src: "images/scenes/pet/pet032.webp", size: "wide" },
    { src: "images/scenes/profile/profile001.webp", size: "wide" },
    { src: "images/scenes/profile/profile002.webp", size: "wide" },
    { src: "images/scenes/profile/profile003.webp", size: "wide" },
    { src: "images/scenes/profile/profile004.webp", size: "wide" },
    { src: "images/scenes/school/school001.webp", size: "wide" },
    { src: "images/scenes/school/school002.webp", size: "wide" },
    { src: "images/scenes/school/school003.webp", size: "wide" },
    { src: "images/scenes/school/school004.webp", size: "wide" },
    { src: "images/scenes/school/school005.webp", size: "wide" },
    { src: "images/scenes/school/school006.webp", size: "wide" },
    { src: "images/scenes/school/school007.webp", size: "wide" },
    { src: "images/scenes/school/school008.webp", size: "wide" },
    { src: "images/scenes/school/school009.webp", size: "wide" },
    { src: "images/scenes/school/school010.webp", size: "wide" },
    { src: "images/scenes/school/school011.webp", size: "wide" },
    { src: "images/scenes/school/school012.webp", size: "wide" },
    { src: "images/scenes/school/school013.webp", size: "wide" },
    { src: "images/scenes/school/school014.webp", size: "wide" },
    { src: "images/scenes/school/school015.webp", size: "wide" },
    { src: "images/scenes/school/school016.webp", size: "wide" },
    { src: "images/scenes/school/school017.webp", size: "wide" },
    { src: "images/scenes/school/school018.webp", size: "wide" },
    { src: "images/scenes/school/school019.webp", size: "wide" },
    { src: "images/scenes/school/school020.webp", size: "wide" },
    { src: "images/scenes/school/school021.webp", size: "wide" },
    { src: "images/scenes/school/school022.webp", size: "wide" },
    { src: "images/scenes/school/school023.webp", size: "wide" },
    { src: "images/scenes/school/school024.webp", size: "wide" },
    { src: "images/scenes/school/school025.webp", size: "wide" },
    { src: "images/scenes/school/school026.webp", size: "wide" },
    { src: "images/scenes/school/school027.webp", size: "wide" },
    { src: "images/scenes/school/school028.webp", size: "wide" },
    { src: "images/scenes/school/school029.webp", size: "wide" },
    { src: "images/scenes/school/school030.webp", size: "wide" },
    { src: "images/scenes/school/school031.webp", size: "wide" },
    { src: "images/scenes/school/school032.webp", size: "wide" },
    { src: "images/scenes/school/school033.webp", size: "wide" },
    { src: "images/scenes/school/school034.webp", size: "wide" },
    { src: "images/scenes/school/school035.webp", size: "wide" },
    { src: "images/scenes/school/school036.webp", size: "wide" },
    { src: "images/scenes/school/school037.webp", size: "wide" },
    { src: "images/scenes/school/school038.webp", size: "wide" },
    { src: "images/scenes/school/school039.webp", size: "wide" },
    { src: "images/scenes/school/school040.webp", size: "wide" },
    { src: "images/scenes/school/school041.webp", size: "wide" },
    { src: "images/scenes/school/school042.webp", size: "wide" },
    { src: "images/scenes/school/school043.webp", size: "wide" },
    { src: "images/scenes/school/school044.webp", size: "wide" },
    { src: "images/scenes/school/school045.webp", size: "wide" },
    { src: "images/scenes/school/school046.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan001.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan002.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan003.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan004.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan005.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan006.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan007.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan008.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan009.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan010.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan011.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan012.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan013.webp", size: "tall" },
    { src: "images/scenes/shichigosan/shichigosan014.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan015.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan016.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan017.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan018.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan019.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan020.webp", size: "tall" },
    { src: "images/scenes/shichigosan/shichigosan021.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan022.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan023.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan024.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan025.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan026.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan027.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan028.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan029.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan030.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan031.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan032.webp", size: "tall" },
    { src: "images/scenes/shichigosan/shichigosan033.webp", size: "tall" },
    { src: "images/scenes/shichigosan/shichigosan034.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan035.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan036.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan037.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan038.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan039.webp", size: "wide" },
    { src: "images/scenes/shichigosan/shichigosan040.webp", size: "wide" },
    { src: "images/scenes/store/store001.webp", size: "wide" },
    { src: "images/scenes/store/store002.webp", size: "wide" },
    { src: "images/scenes/store/store003.webp", size: "wide" },
    { src: "images/scenes/store/store004.webp", size: "wide" },
    { src: "images/scenes/store/store005.webp", size: "wide" },
    { src: "images/scenes/store/store006.webp", size: "wide" },
    { src: "images/scenes/store/store007.webp", size: "wide" },
    { src: "images/scenes/store/store008.webp", size: "wide" },
    { src: "images/scenes/store/store009.webp", size: "wide" },
    { src: "images/scenes/store/store010.webp", size: "wide" },
    { src: "images/scenes/store/store011.webp", size: "wide" },
    { src: "images/scenes/store/store012.webp", size: "wide" },
    { src: "images/scenes/store/store013.webp", size: "wide" },
    { src: "images/scenes/store/store014.webp", size: "wide" },
    { src: "images/scenes/store/store015.webp", size: "wide" },
    { src: "images/scenes/store/store016.webp", size: "wide" },
    { src: "images/scenes/store/store017.webp", size: "wide" },
    { src: "images/scenes/store/store018.webp", size: "wide" },
    { src: "images/scenes/store/store019.webp", size: "wide" },
    { src: "images/scenes/store/store020.webp", size: "wide" },
    { src: "images/scenes/store/store021.webp", size: "wide" },
    { src: "images/scenes/store/store022.webp", size: "wide" },
    { src: "images/scenes/store/store023.webp", size: "wide" },
    { src: "images/scenes/store/store024.webp", size: "wide" },
    { src: "images/scenes/store/store025.webp", size: "wide" },
    { src: "images/scenes/store/store026.webp", size: "wide" },
    { src: "images/scenes/store/store027.webp", size: "wide" },
    { src: "images/scenes/store/store028.webp", size: "wide" },
    { src: "images/scenes/store/store029.webp", size: "wide" },
    { src: "images/scenes/store/store030.webp", size: "tall" },
    { src: "images/scenes/store/store031.webp", size: "tall" },
    { src: "images/scenes/store/store032.webp", size: "wide" },
    { src: "images/scenes/store/store033.webp", size: "wide" },
    { src: "images/scenes/store/store034.webp", size: "wide" },
    { src: "images/scenes/store/store035.webp", size: "wide" },
    { src: "images/scenes/store/store036.webp", size: "wide" },
    { src: "images/scenes/store/store037.webp", size: "wide" },
    { src: "images/scenes/store/store038.webp", size: "wide" },
    { src: "images/scenes/store/store039.webp", size: "wide" }
  ],

  /* ----------------------------------------------------------
     Select Scene（撮影メニュー12種）
     image を差し替えるだけで写真を変更できます
  ---------------------------------------------------------- */
  scenes: [
    { no: "01", en: "Daily",        ja: "日常撮影",
      image: "images/scenes/daily/daily001.webp", alt: "日常撮影の作例写真",
      desc: "何気ない日々の表情や、家族の自然な時間を残す撮影です。",
      gallery: Array.from({ length: 41 }, (_, i) =>
        `images/scenes/daily/daily${String(i + 1).padStart(3, "0")}.webp`) },
    { no: "02", en: "Food Menu",    ja: "商品メニュー撮影",
      image: "images/scenes/product/product-cover.webp", alt: "商品メニュー撮影の作例写真",
      desc: "料理やメニュー、食材の魅力が伝わるように撮影します。",
      gallery: Array.from({ length: 41 }, (_, i) =>
        `images/scenes/product/product${String(i + 1).padStart(3, "0")}.webp`) },
    { no: "03", en: "Store",        ja: "店舗撮影",
      image: "images/scenes/store/store001.webp", alt: "店舗撮影の作例写真",
      desc: "店舗の魅力が伝わる写真撮影に加えて、SNS用の撮影方法をレクチャーするプランもあります。",
      gallery: Array.from({ length: 39 }, (_, i) =>
        `images/scenes/store/store${String(i + 1).padStart(3, "0")}.webp`) },
    { no: "04", en: "Memory",       ja: "記念撮影",
      image: "images/scenes/memory/memory-cover.webp", alt: "記念撮影の作例写真",
      desc: "誕生日や家族の節目を、あたたかな雰囲気で残します。",
      gallery: Array.from({ length: 126 }, (_, i) =>
        `images/scenes/memory/memory${String(i + 1).padStart(3, "0")}.webp`) },
    { no: "05", en: "Pet",          ja: "ペット撮影",
      image: "images/scenes/pet/pet-cover.webp", alt: "ペット撮影の作例写真",
      desc: "大切な家族であるペットの自然な表情を撮影します。",
      gallery: Array.from({ length: 32 }, (_, i) =>
        `images/scenes/pet/pet${String(i + 1).padStart(3, "0")}.webp`) },
    { no: "06", en: "Shichi-Go-San", ja: "七五三・七草",
      image: "images/scenes/shichigosan/shichigosan-cover.webp", alt: "七五三・七草撮影の作例写真",
      desc: "七五三や七草など、成長の節目を自然な空気感とともに残します。",
      gallery: Array.from({ length: 40 }, (_, i) =>
        `images/scenes/shichigosan/shichigosan${String(i + 1).padStart(3, "0")}.webp`) },
    { no: "07", en: "Coming of Age", ja: "成人式",
      image: "images/scenes/coming/coming-cover.webp", alt: "成人式撮影の作例写真",
      desc: "振袖や袴姿の晴れの日を、自然な表情とともに残します。",
      gallery: Array.from({ length: 17 }, (_, i) =>
        `images/scenes/coming/coming${String(i + 1).padStart(3, "0")}.webp`) },
    { no: "08", en: "School Life",  ja: "入学卒業",
      image: "images/scenes/school/school-cover.webp", alt: "入学卒業撮影の作例写真",
      desc: "成長の節目となる大切な瞬間を撮影します。",
      gallery: Array.from({ length: 46 }, (_, i) =>
        `images/scenes/school/school${String(i + 1).padStart(3, "0")}.webp`) },
    { no: "09", en: "Bridal",       ja: "ブライダル撮影",
      image: "images/photos/bridal-top.webp", alt: "光の入る室内で見つめ合う新郎新婦",
      desc: "前撮り、後撮り、ふたりらしい自然なブライダルフォトに対応します。",
      gallery: Array.from({ length: 133 }, (_, i) => i + 1)
        .filter((n) => ![22, 27, 58, 64, 71, 89].includes(n))
        .map((n) => `images/scenes/bridal/bridal${String(n).padStart(3, "0")}.webp`) },
    { no: "10", en: "Kindergarten", ja: "幼稚園保育園撮影",
      image: "images/sq/koukun260228_061.webp", alt: "外遊びでボールを追いかける男の子",
      desc: "園での自然な活動風景や行事を撮影します。" }
  ],

  /* ----------------------------------------------------------
     ポートレート撮影プラン
  ---------------------------------------------------------- */
  plans: [
    {
      en: "DATA PLAN", ja: "データのみプラン", recommended: false,
      copy: ["自由に使える、写真のデータを。", "保存も共有もプリントも、お好きな形で楽しめます。"],
      desc: ["撮影した写真を、データで残したい方向けのシンプルなプランです。",
             "SNSで使いたい方や、ご自身でプリントやアルバムを作りたい方にもおすすめです。"],
      image: { src: "images/plans/data-plan.png", alt: "写真データ納品をイメージしたタブレットと画像ファイルのビジュアル" }
    },
    {
      en: "PHOTO BOOK PLAN", ja: "フォトブック＆データプラン", recommended: true,
      copy: ["写真を、家族の時間として残す。", "スマートフォンの中だけではなく、10年後も手に取って見返せる一冊に。"],
      desc: ["撮影データに加えて、思い出を一冊のフォトブックとして残すプランです。",
             "家族で何度も見返せる形にしたい方におすすめです。"],
      image: { src: "images/plans/photobook-plan.png", alt: "フォトブックと画像データをイメージしたビジュアル" }
    },
    {
      en: "PHOTO PANEL PLAN", ja: "フォトパネル＆データプラン", recommended: false,
      copy: ["思い出を、暮らしの中へ。", "お気に入りの一枚を、毎日目に入る場所に残します。"],
      desc: ["撮影データに加えて、お気に入りの一枚をフォトパネルとして残すプランです。",
             "家の中に飾り、日常の中で写真を楽しみたい方におすすめです。"],
      image: { src: "images/plans/photopanel-plan.png", alt: "室内に飾るフォトパネルと画像データをイメージしたビジュアル" }
    }
  ],

  /* フォトブック・フォトパネルの価格や仕様が決まったらここに追記
     例： { name: "フォトブック A4 20P", price: "¥00,000" } */
  planOptions: [],

  /* 撮影時間別料金（税込） */
  pricing: [
    { en: "30 MINUTES",  ja: "30分撮影",  price: "¥13,000", formValue: "30分",
      notes: ["リタッチ済みデータ", "約50枚前後", "Googleフォト納品"] },
    { en: "60 MINUTES",  ja: "1時間撮影", price: "¥20,000", formValue: "1時間",
      notes: ["リタッチ済みデータ", "撮影内容に応じた枚数", "Googleフォト納品"] },
    { en: "120 MINUTES", ja: "2時間撮影", price: "¥35,000", formValue: "2時間",
      notes: ["リタッチ済みデータ", "撮影内容に応じた枚数", "Googleフォト納品"] },
    { en: "180 MINUTES", ja: "3時間撮影", price: "¥45,000", formValue: "3時間",
      notes: ["リタッチ済みデータ", "撮影内容に応じた枚数", "Googleフォト納品"] }
  ],

  pricingNotes: [
    "撮影した写真は、一枚ずつ色味や明るさを整え、Googleフォトにて納品します。",
    "30分撮影の場合、納品枚数は50枚前後が目安です。",
    "撮影内容、人数、当日の状況によって、納品枚数は前後します。"
  ],

  /* ----------------------------------------------------------
     未確定情報（決まり次第書き換える）
  ---------------------------------------------------------- */
  pending: {
    deliveryDays: "納期は撮影内容や時期によって異なります。",       // 納品までの日数
    travelFee: "遠方の場合は、別途交通費をご相談します。",           // 交通費
    serviceArea: "宮崎県・都城市周辺を中心に出張します。",           // 出張可能エリア
    payment: "お支払い方法は、お問い合わせ時にご案内します。",       // 支払い方法
    cancelPolicy: "撮影日までの日数によってキャンセル料が発生する場合があります。", // キャンセル規定
    rainPolicy: "天候を確認しながら延期、場所変更、屋内撮影などをご相談します。",   // 雨天時
    holidayFee: ""                                                    // 土日祝の追加料金（未定）
  },

  /* ----------------------------------------------------------
     Voice（お客様の声）
     published: false にすると非表示 / order の小さい順に表示
  ---------------------------------------------------------- */
  voices: [
    { image: "images/photos/voice-hirabe.webp", alt: "七五三撮影で笑顔を見せるお子さまの写真",
      name: "平部さま", published: true, order: 1,
      text: "今回、初めてご利用させて頂きました。\nまずは、お願いして良かったなと心から\n思いました。雰囲気作りから、場の和ませ\n方など、全部が本当に楽しかったです！\n\n人見知りな次女の心配をしていましたが\n親でも撮れない、自然な表情をたくさん\n撮って頂けました。\n\n数ヶ月たった今、見返しても\nそのときの思い出が蘇ってくる\nそんな素敵な写真ばかりです。\n\n一生に一度の素敵な記念になりました。\nありがとうございました(●´ω｀●)" },
    { image: "images/photos/voice-nishiida.webp", alt: "プロフィール撮影で自然体の表情を残したお客様の写真",
      name: "西井田さま", published: true, order: 2,
      text: "写真撮影、初めての事でドキドキでしたが、撮られてることを忘れて自然体の写真を撮って頂きました😊\nなにより、カメラマンさんがとても素敵な方で穏やかな気持ちで撮影に臨むことができました🌿\n写真のデータも頂けて、終始とても親切に対応してもらえました😊おすすめです✨" },
    { image: "images/photos/voice-iwakiri.webp", alt: "ハーフバースデー撮影の赤ちゃんの写真",
      name: "岩切さま", published: true, order: 3,
      text: "知人の紹介でお知り合いになり、マタニティフォト、息子のハーフバースデー写真、会社の写真を撮っていただきました。いつも明るくて素敵な方です。短時間で自然体な温かい写真をいつも撮っていただけるので今後ともお願いしたいです💜そして、気になる写真データの方も1週間以内にいつも送ってくださりとてもありがたいです！\n息子の1歳の誕生日フォトもよろしくお願いします💜" },
    { image: "images/photos/voice-miyuki.webp", alt: "成人式撮影の記念写真",
      name: "miyukiさま", published: true, order: 4,
      text: "娘の成人祝いに撮影していただきました。\n写真はもちろん、ヒビノネさんの人柄も素敵で、緊張する事なく楽しい最高の撮影でした💕\n\n次も是非ヒビノネさんにお願いしたいです✨" },
    { image: "images/photos/voice-sonoda.webp", alt: "卒業記念撮影で笑顔を見せる3人の写真", focus: "62% center",
      name: "園田さま", published: true, order: 5,
      text: "娘の卒業記念に写真を撮ってもらいました！\n撮ってる時のヒビノネさんは楽しそうで見てる私も楽しかったです^_^\n子ども達も良い笑顔の写真ばかりでした(^O^)\nまたお願いします♡" }
  ],

  /* ----------------------------------------------------------
     Instagram
     背景写真と投稿（8〜12枚）。published: false で非表示
  ---------------------------------------------------------- */
  instagramBackground: "images/photos/kawasaki015.webp",

  instagramPosts: [
    { image: "images/sq/dsc07177.webp",        url: "", date: "", alt: "湯気の立つ蒸したてのとうもろこし",       published: true, order: 1 },
    { image: "images/sq/morimocha051.webp",    url: "", date: "", alt: "黒い器に盛り付けた前菜の一皿",           published: true, order: 2 },
    { image: "images/sq/tutumi180.webp",       url: "", date: "", alt: "青いおくるみに包まれて眠る赤ちゃん",     published: true, order: 3 },
    { image: "images/sq/temazushi035.webp",    url: "", date: "", alt: "手まり寿司にたれをかける瞬間",           published: true, order: 4 },
    { image: "images/sq/ooura043.webp",        url: "", date: "", alt: "廊下を歩く着物姿の子どもたち",           published: true, order: 5 },
    { image: "images/sq/dsc09467.webp",        url: "", date: "", alt: "かまぼこを作る職人の手元",               published: true, order: 6 },
    { image: "images/sq/koba266.webp",         url: "", date: "", alt: "青い絵皿に盛られたローストビーフ",       published: true, order: 7 },
    { image: "images/sq/yamashita007.webp",    url: "", date: "", alt: "帽子を掲げる着物姿の男の子",             published: true, order: 8 },
    { image: "images/sq/expand029.webp",       url: "", date: "", alt: "編み物をする手元のクローズアップ",       published: true, order: 9 },
    { image: "images/sq/kawanohonoka030.webp", url: "", date: "", alt: "古民家の窓辺に座る着物姿のふたり",       published: true, order: 10 }
  ],

  /* ----------------------------------------------------------
     FAQ（よくある質問）
     published: false で非表示 / order の小さい順に表示
  ---------------------------------------------------------- */
  faq: [
    { category: "撮影場所", order: 1, published: true,
      q: "撮影場所はどこでも大丈夫ですか？",
      a: "宮崎県・都城市周辺を中心に、ご自宅、公園、神社、店舗、スタジオなど、ご希望の場所へ伺います。\n場所によっては撮影許可や施設利用料が必要な場合があります。\n遠方の場合は、別途交通費をご相談します。" },
    { category: "撮影場所", order: 2, published: true,
      q: "スタジオ撮影もできますか？",
      a: "可能です。\n撮影内容やご希望の雰囲気に合わせて、こちらでスタジオを手配できます。\nスタジオ利用料は撮影料金とは別途必要です。" },
    { category: "準備", order: 3, published: true,
      q: "ヘアセットやメイクもお願いできますか？",
      a: "美容師の紹介が可能です。\nヘアセット、メイク、着付けなど、ご希望の内容をお問い合わせ時にお知らせください。\n美容師への依頼料や交通費は、撮影料金とは別途必要です。" },
    { category: "撮影", order: 4, published: true,
      q: "子どもが人見知りですが、大丈夫ですか？",
      a: "大丈夫です。\nすぐに撮影を始めるのではなく、会話や遊びを通して少しずつ距離を縮めます。\nお子さまのペースを優先し、無理に撮影を進めません。" },
    { category: "撮影", order: 5, published: true,
      q: "撮影時間はどれを選べばよいですか？",
      a: "プロフィール撮影や短時間の記念撮影は、30分から1時間が目安です。\n家族撮影、七五三、複数の場所での撮影は、1時間から2時間がおすすめです。\nイベントや長時間の密着撮影は、2時間から3時間をご検討ください。\n内容が決まっていない場合は、ご相談内容に合わせてご提案します。" },
    { category: "納品", order: 6, published: true,
      q: "納品枚数は何枚ですか？",
      a: "30分撮影の場合は、50枚前後が目安です。\n撮影時間、人数、撮影内容、当日の状況によって納品枚数は変わります。" },
    { category: "納品", order: 7, published: true,
      q: "写真はどのように納品されますか？",
      a: "一枚ずつ色味や明るさを整えたうえで、Googleフォトにて納品します。\nダウンロード方法についても、納品時にご案内します。" },
    { category: "納品", order: 8, published: true,
      q: "納品までどれくらいかかりますか？",
      a: "納期は撮影内容や時期によって異なります。\n目安の納期は、お問い合わせ時にご案内します。" },   /* ← 納期が決まったら書き換え */
    { category: "当日", order: 9, published: true,
      q: "雨の日はどうなりますか？",
      a: "屋外撮影の場合は、天候を確認しながら延期、場所変更、屋内撮影などをご相談します。\n安全と写真の仕上がりを優先して判断します。" },
    { category: "予約", order: 10, published: true,
      q: "キャンセルや日程変更はできますか？",
      a: "可能です。\nただし、撮影日までの日数によってキャンセル料が発生する場合があります。\nスタジオや美容師を手配済みの場合は、それぞれのキャンセル料が発生する場合があります。" },
    { category: "データ利用", order: 11, published: true,
      q: "撮影データをSNSに掲載しても大丈夫ですか？",
      a: "個人利用の範囲で、ご自由に掲載できます。\n商用利用、広告利用、販売目的で使用する場合は、事前にご相談ください。" },
    { category: "データ利用", order: 12, published: true,
      q: "写真をホームページやSNSに掲載されることはありますか？",
      a: "掲載許可をいただいた写真のみ、ヒビノネ写真館のホームページやSNSで紹介します。\n許可なく掲載することはありません。" },
    { category: "法人・団体", order: 13, published: true,
      q: "商品撮影や店舗撮影も依頼できますか？",
      a: "可能です。\n商品撮影は、盛り付けや調理を含めて一貫して対応できます。\n店舗撮影では、店舗写真、スタッフ写真、商品写真などに加えて、SNS用の撮影方法をレクチャーするプランも用意できます。\n撮影内容によって料金が異なるため、個別にお見積もりします。" },
    { category: "法人・団体", order: 14, published: true,
      q: "イベントや幼稚園、保育園の撮影も依頼できますか？",
      a: "可能です。\n発表会、地域イベント、園行事、日常保育など、撮影内容に合わせて対応します。\n参加人数、拘束時間、納品方法などを確認したうえでお見積もりします。" },
    { category: "商品", order: 15, published: true,
      q: "フォトブックやフォトパネルは追加できますか？",
      a: "可能です。\nデータのみで申し込んだあとに、フォトブックやフォトパネルを追加できる場合があります。\n追加料金や制作期間は、個別にご案内します。" },
    { category: "支払い", order: 16, published: true,
      q: "支払い方法は何がありますか？",
      a: "お支払い方法の詳細は、お問い合わせ時にご案内します。" },   /* ← 対応方法が決まったら書き換え */
    { category: "予約", order: 17, published: true,
      q: "予約はいつまでにすればよいですか？",
      a: "空きがあれば直前でも対応できます。\n七五三、入学卒業、成人式、繁忙期の土日祝は予約が集中するため、早めの相談をおすすめします。" },
    { category: "相談", order: 18, published: true,
      q: "まだ撮影内容が決まっていなくても相談できますか？",
      a: "大丈夫です。\n撮りたい雰囲気や残したい目的が曖昧な段階でも、ご希望を聞きながら撮影内容をご提案します。" }
  ],

  /* ----------------------------------------------------------
     フォームの選択肢
  ---------------------------------------------------------- */
  formOptions: {
    sceneTypes: ["日常撮影","商品メニュー撮影","店舗撮影","記念撮影","ペット撮影",
                 "七五三・七草","成人式","入学卒業","ブライダル撮影","幼稚園保育園撮影",
                 "その他","まだ決まっていない"],
    plans: ["データのみ","フォトブック＆データ","フォトパネル＆データ","相談して決めたい"],
    durations: ["30分","1時間","2時間","3時間","相談して決めたい"],
    locations: ["ロケーション撮影","ご自宅","スタジオ撮影","店舗","幼稚園、保育園","その他","まだ決まっていない"],
    studio: ["希望する","希望しない","相談したい"],
    hairmake: ["希望する","希望しない","相談したい"]
  }
};
